### ISSUE TITLE
::selection selektorundan istifadə edə bilərsiniz

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [muradorucov/MyPortfolio#1]
[🔗](https://developer.mozilla.org/en-US/docs/Web/CSS/::selection)

```css
::selection {
    color: #fff;
    background-color: #ffc107;
}
```
Saytınızda qəşəng göründü. :)
